### ISSUE TITLE
info/ directory can't be served by Apache by default

### ISSUE THREAD

**Issue by rmosolgo** [rubygems/rubygems-generate_index#25]
### Describe the problem as clearly as you can

After running `gem generate_index`, Apache can't serve `info/` files. 

The first time this happened, I manually `chmod +x`'d the `info/` directory and it started working again. But I'm finding that after each time I `gem generate_index`, I need to `chmod +x info` again. I noticed that the other directories already have `x`, and I think that `info` should have it too. That way, Apache could serve it without any trouble. 

I see that info is created with special permissions: 

https://github.com/rubygems/rubygems-generate_index/blob/f90312689aa0364b715e232552004a3374122478/lib/rubygems/indexer.rb#L218-L219

But I'm not sure why this is ... I'm going to investigate how those _other_ directories are created and try creating this one the same way, or updating those permissions.

### Did you try upgrading RubyGems?

Yes 

### Post steps to reproduce the problem
```
gem generate_index --directory=/your/directory
ls -l /your/directory
```

Then, you can see how `info/` has a different permission. Here's an example from the test suite: 

```
$ ls -l tmp/test_rubygems_20240618-78633-mb9hwh/indexer
total 64
drwxr-xr-x  15 rmosolgo  staff  480 Jun 18 08:43 gems
drwx------  10 rmosolgo  staff  320 Jun 18 08:43 info
-rw-r--r--   1 rmosolgo  staff  222 Jun 18 08:43 latest_specs.4.8
-rw-r--r--   1 rmosolgo  staff  151 Jun 18 08:43 latest_specs.4.8.gz
-rw-r--r--   1 rmosolgo  staff   30 Jun 18 08:43 names
-rw-r--r--   1 rmosolgo  staff  127 Jun 18 08:43 prerelease_specs.4.8
-rw-r--r--   1 rmosolgo  staff  115 Jun 18 08:43 prerelease_specs.4.8.gz
drwxr-xr-x   3 rmosolgo  staff   96 Jun 18 08:43 quick
-rw-r--r--   1 rmosolgo  staff  230 Jun 18 08:43 specs.4.8
-rw-r--r--   1 rmosolgo  staff  155 Jun 18 08:43 specs.4.8.gz
-rw-r--r--   1 rmosolgo  staff  396 Jun 18 08:43 versions
```

### Which command did you run?

`gem generate_index`

### What were you expecting to happen?

I was expecting a result which Apache could serve without further changes. 

### What actually happened?

`Info/` files weren't served which caused Bundler to fall back to a full-index resolution (see #22) 

### Run `gem env` and paste the output below

```
$ gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 3.5.12
  - RUBY VERSION: 3.3.3 (2024-06-12 patchlevel 89) [x86_64-linux]
  - INSTALLATION DIRECTORY: /home/rdmosolgo/.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0
  - USER INSTALLATION DIRECTORY: /home/rdmosolgo/.gem/ruby/3.3.0
  - RUBY EXECUTABLE: /home/rdmosolgo/.rbenv/versions/3.3.3/bin/ruby
  - GIT EXECUTABLE: /usr/bin/git
  - EXECUTABLE DIRECTORY: /home/rdmosolgo/.rbenv/versions/3.3.3/bin
  - SPEC CACHE DIRECTORY: /home/rdmosolgo/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /home/rdmosolgo/.rbenv/versions/3.3.3/etc
  - RUBYGEMS PLATFORMS:
     - ruby
     - x86_64-linux
  - GEM PATHS:
     - /home/rdmosolgo/.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0
     - /home/rdmosolgo/.gem/ruby/3.3.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => true
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /home/rdmosolgo/.rbenv/versions/3.3.3/bin
     - /home/rdmosolgo/.rbenv/libexec
     - /home/rdmosolgo/.rbenv/plugins/ruby-build/bin
     - /home/rdmosolgo/bin
     - /home/rdmosolgo/.local/bin
     - /home/rdmosolgo/.rbenv/shims
     - /home/rdmosolgo/.rbenv/bin
     - /usr/local/sbin
     - /usr/local/bin
     - /usr/sbin
     - /usr/bin
     - /sbin
     - /bin
     - /usr/games
     - /usr/local/games
     - /snap/bin
```

**Comment by segiddins** [comment]
@rmosolgo is this fixed now?

**Comment by rmosolgo** [comment]
Yes, sorry I didn't follow up and close it :+1:
